#
# Build stage
#
FROM maven:3.8.4-openjdk-11-slim AS build
COPY src /home/app/src
COPY pom.xml /home/app
RUN mvn -f /home/app/pom.xml clean package

#
# Package stage
#
FROM adoptopenjdk/openjdk11:alpine
COPY --from=build /home/app/target/kafka-data-pipelines-1.0-jar-with-dependencies.jar /usr/local/app/kafka-data-pipelines.jar
WORKDIR /usr/local/app

RUN wget https://apache.mirror.iphh.net/spark/spark-3.2.0/spark-3.2.0-bin-hadoop3.2-scala2.13.tgz && \
    tar -xvzf spark-3.2.0-bin-hadoop3.2-scala2.13.tgz && \
    mv spark-3.2.0-bin-hadoop3.2-scala2.13 spark && \
    rm spark-3.2.0-bin-hadoop3.2-scala2.13.tgz

RUN apk update && apk add bash

# keep container running
ENTRYPOINT ["tail", "-f", "/dev/null"]